filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

processors:
  - add_cloud_metadata: ~

output.logstash:
  hosts: ["logstash:5044"]

filebeat.inputs:
  # 采集系统日志
    - type: log
      paths: 
        - /var/log/nginx/*.log
