version: '3'
# 定义服务mysql,redis,php,nginx
services:
    #数据库
    mysql57:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=123123
            #- MYSQL_USER=user
            #- MYSQL_PASSWORD=password
        volumes:
            #配置文件
            - ./conf/mysql/my.cnf:/etc/mysql/my.cnf:ro
            #数据目录
            - ./mysql/:/var/lib/mysql/:rw
            #查询日志文件
            #- ./logs/mysql/query_mysql.log:/var/logs/mysql/query.mysql.log:rw
            #慢查询日志文件
            #- ./logs/mysql/slow_mysql.log:/var/logs/mysql/slow.mysql.log:rw
        ports:
            - "9006:3306"
        container_name: mysql57
    redis:
        image: daocloud.io/library/redis:5.0-rc4-alpine3.8
        expose:
            - "6379"
        container_name: redis
    memcached:
        image: memcached:1.5.12-alpine
        expose:
            - "11211"
        container_name: memcached
    php72:
        depends_on:
            - mysql57
            - redis
        build: ./php72
        restart: always
        volumes:
            - ./php72/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
            - ../www/:/data/www/:rw
            #- ./logs/php72/fpm-php.www.log:/var/log/fpm-php.www.log:rw
        expose:
            - "9000"
        container_name: php72
    php71:
        depends_on:
            - mysql57
            - redis
        build: ./php71
        restart: always
        volumes:
            - ./php71/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
            - ../www/:/data/www/:rw
            #- ./logs/php71/fpm-php.www.log:/var/log/fpm-php.www.log:rw
        expose:
            - "9000"
        container_name: php71
    php70:
        depends_on:
            - mysql57
            - redis
        build: ./php70
        restart: always
        volumes:
            - ./php70/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
            - ../www/:/data/www/:rw
            #- ./logs/php70/fpm-php.www.log:/var/log/fpm-php.www.log:rw
        expose:
            - "9000"
        container_name: php70
    php56:
        depends_on:
            - mysql57
            - redis
        build: ./php56
        restart: always
        volumes:
            - ./php56/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
            - ../www/:/data/www/:rw
            #- ./logs/php56/fpm-php.www.log:/var/log/fpm-php.www.log:rw
        expose:
            - "9000"
        container_name: php56
    php55:
        depends_on:
            - mysql57
            - redis
        build: ./php55
        restart: always
        volumes:
            - ./php55/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
            - ../www/:/data/www/:rw
            #- ./logs/php55/fpm-php.www.log:/var/log/fpm-php.www.log:rw
        expose:
            - "9000"
        container_name: php55
    #服务器nginx
    web_server:
        image: nginx:1.15.6
        ports:
            - '80:80'
            - '443:443'
        volumes:
        #主配置
            - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        #虚拟主机配置
            - ./conf/nginx/conf.d/:/etc/nginx/conf.d/:rw
        #web目录
            - ../www/:/data/www/:rw
        #证书目录
            - ./certificates/:/etc/letsencrypt/:ro
        #日志目录
            - ./logs/nginx/:/var/log/nginx/:rw
        restart: always
        container_name: nginx
    #mysql管理
    phpmyadmin:
        depends_on:
            - mysql57
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_HOST=mysql57
        ports:
            - "9906:80"
        container_name: phpmyadmin
    #redis管理
    phpredisadmin:
        build: ./phpRedisAdmin
        environment:
            # - ADMIN_USER=admin
            # - ADMIN_PASS=admin
            - REDIS_1_HOST=redis
            - REDIS_1_PORT=6379
        links:
            - redis
        ports:
            - "9379:80"
        container_name: phpredisadmin
    #文档系统
    showdoc:
        build: ./showdoc
        volumes:
        #项目文件
            - ./showdoc/:/var/www/html/:rw
        ports:
            - "9015:80"
        container_name: showdoc
    #部分项目需要该版本兼容
    php559:
        build: ./php559
        volumes:
        #项目目录
            - ../www/:/data/www/:rw
        #虚拟主机
            - ./apache2/sites-enabled/:/etc/apache2/sites-enabled/:ro
        #主配置文件
            - ./apache2/apache2.conf:/etc/apache2/apache2.conf:ro
        #php.ini文件
            - ./php559/php.ini:/etc/php5/apache2/php.ini:ro
        #日志目录
            - ./logs/apache2/:/var/log/apache2/:rw
        container_name: php559
        #临时开放8080
        ports:
            - "8080:80"
        #仅对容器内开放访问
        ports:
            - "8080:80"
        expose:
            - 80
    acme:
        image: neilpang/acme.sh
        volumes:
            - ./certificates/:/acme.sh:rw
        command: daemon
        network_mode: "host"
        container_name: acme
    #ftp服务器
    ftpd_server:
        image: stilliard/pure-ftpd:hardened
        container_name: pure-ftpd
        ports:
            - "21:21"
            - "30000-30009:30000-30009"
        volumes:
            - "../:/home/ftpusers/:rw"
            - "./docker-pure-ftpd/passwd:/etc/pure-ftpd/passwd"
        environment:
            PUBLICHOST: "localhost"
        restart: always
    svn:
        build: ./docker-subversion
        container_name: svn
        ports:
            - "9200:80"
            - "9201:443"
        volumes: 
            - ./svn/svn:/var/local/svn:rw
            - ./svn/svn_backup:/var/svn-backup:rw
            - ./svn/svn_conf:/etc/apache2/dav_svn:rw
        restart: always
    gitlab:
        image: gitlab/gitlab-ce:latest
        container_name: gitlab
        ports:
            - "10443:443"
            - "10080:80"
            - "10022:22"
        volumes:
            - "./gitlab/config:/etc/gitlab:rw"
            - "./gitlab/logs:/var/log/gitlab:rw"
            - "./gitlab/data:/var/opt/gitlab:rw"
        restart: always
    #下载工具
    you-get:
        build: ./you-get
        container_name: you-get
        stdin_open: true
        tty: true
        #下载目录
        volumes:
            - "../Downloads:/data/download:rw"
    #代理ip池
    proxy_pool:
        volumes:
            - ./proxy_pool:/usr/src/app
        # ports:
        #     - "5010:5010"
        links:
            - redis
        build: ./proxy_pool/Docker
        container_name: proxy_pool
    #下载器
    h5ai:
        image: bixidock/h5ai
        volumes:
            - ../Downloads:/var/www:rw
        restart: always
    aria2:
        image: wahyd4/aria2-ui:h5ai
        ports:
            - "9080:80"
            - "9443:443"
            - "6800:6800"
        volumes:
            - ../Downloads:/var/www:rw
        # volumes:
        #   - /some_folder:/root/conf/key
        #   - ~/test/aria2.conf:/root/conf/aria2.conf
        environment:
            - DOMAIN=:80
            - PLEX_CLAIM=claim-KpMm8oqWA6a1rFV3zFqS
            # - SSL=true
            # - RPC_SECRET=Hello
            - ARIA2_USER=lestat
            - ARIA2_PWD=123123
            - ENABLE_AUTH=true
        links:
            - h5ai:file-manager
        restart: always

networks:
  default:
    driver: bridge