version: '3'
services:
    #数据库-master
    mysql57:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=password
            #- MYSQL_USER=user
            #- MYSQL_PASSWORD=password
        volumes:
            #配置文件
            - ./src/mysql/my.cnf:/etc/mysql/my.cnf:ro
            #数据目录
            #- ./mysql/:/var/lib/mysql/:rw
            #查询日志文件
            #- ./logs/mysql/query_mysql.log:/var/logs/mysql/query.mysql.log:rw
            #慢查询日志文件
            #- ./logs/mysql/slow_mysql.log:/var/logs/mysql/slow.mysql.log:rw
        ports:
            - "9006:3306"
        container_name: mysql57
    #数据库-slave
    mysql57-slave:
        depends_on:
            - mysql57
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=password
            #- MYSQL_USER=user
            #- MYSQL_PASSWORD=password
        volumes:
            #配置文件
            - ./src/mysql-slave/my.cnf:/etc/mysql/my.cnf:ro
            #数据目录
            #- ./mysql-slave/:/var/lib/mysql/:rw
            #查询日志文件
            #- ./logs/mysql/query_mysql.log:/var/logs/mysql/query.mysql.log:rw
            #慢查询日志文件
            #- ./logs/mysql/slow_mysql.log:/var/logs/mysql/slow.mysql.log:rw
        ports:
            - "9007:3306"
        container_name: mysql57-slave
    redis:
        image: daocloud.io/library/redis:5.0-rc4-alpine3.8
        ports:
            - "6379:6379"
        container_name: redis
    memcached:
        image: memcached:1.5.12-alpine
        expose:
            - "11211"
        container_name: memcached
    php72:
        depends_on:
            - mysql57
            - redis
        build: ./src/php72
        restart: always
        volumes:
            - ./src/php72/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
            - ./www/:/data/www/:rw
            #- ./logs/php72/fpm-php.www.log:/var/log/fpm-php.www.log:rw
        expose:
            - "9000"
        container_name: php72
    php71:
        depends_on:
            - mysql57
            - redis
        build: ./src/php71
        restart: always
        volumes:
            - ./src/php71/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
            - ./www/:/data/www/:rw
            #- ./logs/php71/fpm-php.www.log:/var/log/fpm-php.www.log:rw
        expose:
            - "9000"
        container_name: php71
    php70:
        depends_on:
            - mysql57
            - redis
        build: ./src/php70
        restart: always
        volumes:
            - ./src/php70/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
            - ./www/:/data/www/:rw
            #- ./logs/php70/fpm-php.www.log:/var/log/fpm-php.www.log:rw
        expose:
            - "9000"
        container_name: php70
    php56:
        depends_on:
            - mysql57
            - redis
        build: ./src/php56
        restart: always
        volumes:
            - ./src/php56/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
            - ./www/:/data/www/:rw
            #- ./logs/php56/fpm-php.www.log:/var/log/fpm-php.www.log:rw
        expose:
            - "9000"
        container_name: php56
    php55:
        depends_on:
            - mysql57
            - redis
        build: ./src/php55
        restart: always
        volumes:
            - ./src/php55/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
            - ./www/:/data/www/:rw
            #- ./logs/php55/fpm-php.www.log:/var/log/fpm-php.www.log:rw
        expose:
            - "9000"
        container_name: php55
    #服务器nginx(openresty)
    openresty:
        image: openresty/openresty
        ports:
            - '80:80'
            - '443:443'
        volumes:
        #主配置
            - ./src/openresty/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
        #虚拟主机配置
            - ./src/openresty/conf.d/:/etc/nginx/conf.d/:rw
        #lua脚本目录
            - ./openresty/:/usr/local/openresty/nginx/src/:ro
        #web目录
            - ./www/:/data/www/:rw
        #证书目录
            - ./certificates/:/etc/letsencrypt/:ro
        #日志目录
            - ./logs/openresty/:/var/log/nginx/:rw
        restart: always
        container_name: openresty
    #mysql管理
    phpmyadmin:
        depends_on:
            - mysql57
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_HOST=mysql57
        ports:
            - "9906:80"
        container_name: phpmyadmin
    #redis管理
    phpredisadmin:
        build: ./src/phpRedisAdmin
        environment:
            # - ADMIN_USER=admin
            # - ADMIN_PASS=admin
            - REDIS_1_HOST=redis
            - REDIS_1_PORT=6379
        links:
            - redis
        ports:
            - "9379:80"
        container_name: phpredisadmin
    #文档系统
    showdoc:
        build: ./src/showdoc
        volumes:
        #项目文件
            - ./showdoc/:/var/www/html/:rw
        ports:
            - "9015:80"
        container_name: showdoc
    #下载工具
    you-get:
        build: ./src/you-get
        container_name: you-get
        stdin_open: true
        tty: true
        #下载目录
        volumes:
            - "./Downloads:/data/download:rw"
    #代理ip池
    proxy_pool:
        volumes:
            - ./src/proxy_pool:/usr/src/app
        # ports:
        #     - "5010:5010"
        links:
            - redis
        build: ./src/proxy_pool/Docker
        container_name: proxy_pool
    #下载器
    h5ai:
        image: bixidock/h5ai
        volumes:
            - ./Downloads:/var/www:rw
        restart: always
        container_name: h5ai
    aria2:
        image: wahyd4/aria2-ui:h5ai
        ports:
            - "9080:80"
            - "9443:443"
            - "6800:6800"
        volumes:
            - ./Downloads:/var/www:rw
        # volumes:
        #   - /some_folder:/root/conf/key
        #   - ~/test/aria2.conf:/root/conf/aria2.conf
        environment:
            - DOMAIN=:80
            - PLEX_CLAIM=claim-KpMm8oqWA6a1rFV3zFqS
            # - SSL=true
            # - RPC_SECRET=Hello
            - ARIA2_USER=lestat
            - ARIA2_PWD=123123
            - ENABLE_AUTH=true
        links:
            - h5ai:file-manager
        restart: always
        container_name: aria2

networks:
  default:
    driver: bridge